import { useState } from "react";
import { ProgressiveMessageList } from "./progressive-message-list";
import { CustomerIntelligenceSidebarOptimized } from "./customer-intelligence-sidebar-optimized";

// This wrapper combines the message list with the customer intelligence sidebar
export function InboxWithSidebar() {
  const [selectedMessageId, setSelectedMessageId] = useState<string | null>("1");

  // Mock messages - should match the ones in ProgressiveMessageList
  const allMessages = [
    {
      id: "1",
      sender: "Johan Lagerström",
      subject: "Bokning av tid",
      preview: "Hej, jag vill boka en tid...",
      time: "19:22",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
      unread: true,
      sla: "1m",
      slaStatus: "breach" as const,
      slaMinutesLeft: 1,
      priority: "sprint" as const,
      warmth: "hot" as const,
      lifecycle: "active" as const,
      intent: "Bokning",
      confidence: 98,
      recommendedAction: "Bekräfta tid",
      tags: ["Bokning", "Sprint"],
      slaRisk: "breach" as const,
      slaTime: "1m",
      sentiment: "excited" as const,
      isVIP: false,
      revenuePotential: "high" as const,
      journeyStage: "lead" as const,
      isDuplicate: false,
      timeSinceLastVisit: "Aldrig",
      interactionCount: 1,
      conversionProbability: 85,
      referralSource: "instagram" as const,
      isRead: false,
      isStagnant: false,
      suggestedReply: "Hej Johan! Självklart! Vi har lediga tider på torsdag 14:00 eller fredag 10:30. Vilken passar bäst?",
      suggestedSlots: ["Torsdag 14:00", "Fredag 10:30", "Måndag 13:00"],
      detectedLanguage: "sv" as const,
      upsellOpportunity: "Kunden frågade om fillers → föreslå konsultation paket",
      lifetimeValue: 0,
      needsFollowup: true,
      avgResponseTime: "N/A",
      bestTimeToReply: "18:00-20:00",
      assignedTo: "Sara Lindberg",
      internalNotes: ["Första kontakten", "Verkar mycket intresserad"],
      handoffStatus: "in-progress" as const,
      churnRisk: "low" as const,
      treatmentHistory: [] as string[],
      medicalFlags: [] as string[],
      consentStatus: { gdpr: false, photos: false, marketing: false },
      insurance: undefined,
      isTyping: false,
      reactions: [] as string[],
      hasVoiceNote: false,
      slaPrediction: "will-breach" as const,
    },
    {
      id: "2",
      sender: "Anna Karlsson",
      subject: "Akut ombokningsfråga",
      preview: "Måste tyvärr ställa in imorgon...",
      time: "18:45",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
      unread: true,
      sla: "30m",
      slaStatus: "breach" as const,
      slaMinutesLeft: 30,
      priority: "sprint" as const,
      warmth: "warm" as const,
      lifecycle: "active" as const,
      intent: "Omboka",
      confidence: 95,
      recommendedAction: "Föreslå ny tid",
      tags: ["Omboka", "Sprint"],
      slaRisk: "breach" as const,
      slaTime: "30m",
      sentiment: "worried" as const,
      isVIP: true,
      revenuePotential: "premium" as const,
      journeyStage: "customer" as const,
      isDuplicate: false,
      timeSinceLastVisit: "2 veckor",
      interactionCount: 8,
      conversionProbability: 95,
      referralSource: "referral" as const,
      isRead: true,
      isStagnant: false,
      suggestedReply: "Hej Anna! Inga problem, jag förstår. Vad sägs om onsdag 15:00 eller torsdag 11:00?",
      suggestedSlots: ["Onsdag 15:00", "Torsdag 11:00", "Fredag 14:00"],
      detectedLanguage: "sv" as const,
      upsellOpportunity: "Återkommande VIP → erbjud premium membership",
      lifetimeValue: 48500,
      needsFollowup: false,
      avgResponseTime: "12 min",
      bestTimeToReply: "17:00-19:00",
      assignedTo: "Dr. Eriksson",
      internalNotes: ["VIP-kund sedan 2 år", "Alltid mycket nöjd", "Prefererar Dr. Eriksson"],
      handoffStatus: "in-progress" as const,
      churnRisk: "low" as const,
      treatmentHistory: ["Fillers (2024-02)", "Botox (2024-01)", "Konsultation (2023-11)"],
      medicalFlags: ["Allergi: Latex"],
      consentStatus: { gdpr: true, photos: true, marketing: true },
      insurance: "Folksam Premium",
      isTyping: true,
      reactions: ["👍", "❤️"],
      hasVoiceNote: false,
      slaPrediction: "at-risk" as const,
    },
    {
      id: "3",
      sender: "Erik Svensson",
      subject: "Prisfråga konsultation",
      preview: "Hej! Vad kostar en första konsultation?",
      time: "15:20",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
      unread: true,
      sla: "4h",
      slaStatus: "warning" as const,
      slaMinutesLeft: 135,
      priority: "critical" as const,
      warmth: "cold" as const,
      lifecycle: "new" as const,
      intent: "Prisfråga",
      confidence: 92,
      recommendedAction: "Skicka prislista",
      tags: ["Prisfråga", "Critical"],
      slaRisk: "warning" as const,
      slaTime: "4h",
      sentiment: "neutral" as const,
      isVIP: false,
      revenuePotential: "medium" as const,
      journeyStage: "lead" as const,
      isDuplicate: true,
      duplicateCount: 2,
      timeSinceLastVisit: "Aldrig",
      interactionCount: 2,
      conversionProbability: 45,
      referralSource: "google" as const,
      isRead: false,
      isStagnant: false,
      competitorMentioned: "Rival Klinik",
      suggestedReply: "Hej Erik! Första konsultationen kostar 500 kr och inkluderar en komplett analys. Vill du boka in en tid?",
      suggestedSlots: ["Måndag 10:00", "Tisdag 14:00", "Onsdag 16:00"],
      detectedLanguage: "sv" as const,
      upsellOpportunity: undefined,
      lifetimeValue: 0,
      needsFollowup: true,
      avgResponseTime: "N/A",
      bestTimeToReply: "15:00-17:00",
      assignedTo: undefined,
      internalNotes: ["Nämner konkurrent - var försiktig", "Prisjämför", "Mailade 2 ggr redan"],
      handoffStatus: "unassigned" as const,
      churnRisk: "high" as const,
      treatmentHistory: [] as string[],
      medicalFlags: [] as string[],
      consentStatus: { gdpr: false, photos: false, marketing: false },
      insurance: undefined,
      isTyping: false,
      reactions: [] as string[],
      hasVoiceNote: false,
      slaPrediction: "at-risk" as const,
    },
    {
      id: "4",
      sender: "Maria Andersson",
      subject: "Uppföljning behandling",
      preview: "Hur ska jag gå vidare efter första...",
      time: "12:30",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
      unread: true,
      priority: "high" as const,
      warmth: "warm" as const,
      lifecycle: "active" as const,
      intent: "Uppföljning",
      confidence: 89,
      recommendedAction: "Boka uppföljning",
      tags: ["Uppföljning", "High"],
      slaRisk: "safe" as const,
      slaTime: "12:30",
      sentiment: "happy" as const,
      isVIP: false,
      revenuePotential: "high" as const,
      journeyStage: "customer" as const,
      isDuplicate: false,
      timeSinceLastVisit: "1 månad",
      interactionCount: 4,
      conversionProbability: 90,
      referralSource: "facebook" as const,
      isRead: false,
      isStagnant: false,
      suggestedReply: "Hej Maria! Så kul att höra från dig! För bästa resultat rekommenderar vi uppföljning om 2 veckor. Passar torsdag 13:00?",
      suggestedSlots: ["Torsdag 13:00", "Fredag 15:00", "Måndag 11:00"],
      detectedLanguage: "sv" as const,
      upsellOpportunity: "Nöjd med botox → föreslå fillers som komplement",
      lifetimeValue: 8900,
      needsFollowup: false,
      avgResponseTime: "45 min",
      bestTimeToReply: "12:00-14:00",
      assignedTo: "Sara Lindberg",
      internalNotes: ["Genomgick första behandling för 1 månad sen", "Mycket nöjd hittills"],
      handoffStatus: "waiting" as const,
      churnRisk: "low" as const,
      treatmentHistory: ["Botox (2024-02)"],
      medicalFlags: [] as string[],
      consentStatus: { gdpr: true, photos: false, marketing: true },
      insurance: undefined,
      isTyping: false,
      reactions: ["😊"],
      hasVoiceNote: true,
      slaPrediction: "safe" as const,
    },
    {
      id: "5",
      sender: "Lisa Nilsson",
      subject: "Fakturafråga",
      preview: "Kan ni skicka en kopia...",
      time: "11:15",
      avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&h=100&fit=crop",
      priority: "normal" as const,
      warmth: "warm" as const,
      lifecycle: "returning" as const,
      intent: "Faktura",
      confidence: 96,
      recommendedAction: "Skicka faktura",
      tags: ["Faktura", "Normal"],
      slaRisk: "safe" as const,
      slaTime: "11:15",
      sentiment: "neutral" as const,
      isVIP: true,
      revenuePotential: "premium" as const,
      journeyStage: "vip" as const,
      isDuplicate: false,
      timeSinceLastVisit: "1 vecka",
      interactionCount: 15,
      conversionProbability: 100,
      referralSource: "referral" as const,
      isRead: true,
      isStagnant: false,
      suggestedReply: "Hej Lisa! Självklart, jag skickar fakturan direkt via mail. Den bör vara framme inom några minuter.",
      suggestedSlots: [] as string[],
      detectedLanguage: "sv" as const,
      upsellOpportunity: "VIP med hög LTV → föreslå årligt premium-paket",
      lifetimeValue: 127500,
      needsFollowup: false,
      avgResponseTime: "8 min",
      bestTimeToReply: "10:00-12:00",
      assignedTo: "Ekonomi - Anna",
      internalNotes: ["Toppkund!", "Alltid betalar i tid", "Rekommenderat 3 nya kunder"],
      handoffStatus: "completed" as const,
      churnRisk: "low" as const,
      treatmentHistory: ["Premium Paket (2024-01)", "Fillers (2023-11)", "Botox (2023-10)", "Laserfraktionering (2023-09)"],
      medicalFlags: [] as string[],
      consentStatus: { gdpr: true, photos: true, marketing: true },
      insurance: "Skandia VIP",
      isTyping: false,
      reactions: ["❤️", "👍", "😊"],
      hasVoiceNote: false,
      slaPrediction: "safe" as const,
    },
    {
      id: "6",
      sender: "Peter Johansson",
      subject: "Tack för behandlingen",
      preview: "Jag ville bara säga tack...",
      time: "10:05",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
      priority: "normal" as const,
      warmth: "hot" as const,
      lifecycle: "active" as const,
      intent: "Feedback",
      confidence: 99,
      recommendedAction: "Tacka och be om recension",
      tags: ["Feedback", "Normal"],
      slaRisk: "safe" as const,
      slaTime: "10:05",
      sentiment: "happy" as const,
      isVIP: false,
      revenuePotential: "low" as const,
      journeyStage: "customer" as const,
      isDuplicate: false,
      timeSinceLastVisit: "3 dagar",
      interactionCount: 3,
      conversionProbability: 75,
      referralSource: "tiktok" as const,
      isRead: true,
      isStagnant: false,
      suggestedReply: "Hej Peter! Tack själv, så kul att du är nöjd! 😊 Skulle betyda mycket om du ville dela din upplevelse på Google!",
      suggestedSlots: [] as string[],
      detectedLanguage: "sv" as const,
      upsellOpportunity: undefined,
      lifetimeValue: 3500,
      needsFollowup: false,
      avgResponseTime: "1h 20min",
      bestTimeToReply: "09:00-11:00",
      assignedTo: "Sara Lindberg",
      internalNotes: ["Perfekt tillfälle att be om recension!", "Mycket nöjd kund"],
      handoffStatus: "waiting" as const,
      churnRisk: "medium" as const,
      treatmentHistory: ["Botox (2024-03)"],
      medicalFlags: [] as string[],
      consentStatus: { gdpr: true, photos: false, marketing: false },
      insurance: undefined,
      isTyping: false,
      reactions: [] as string[],
      hasVoiceNote: false,
      slaPrediction: "safe" as const,
    },
  ];

  const selectedMessage = allMessages.find(m => m.id === selectedMessageId) || null;

  return (
    <div className="flex h-full">
      {/* Message List - 60% */}
      <div className="w-[60%] border-r border-gray-200">
        <ProgressiveMessageList 
          onSelectMessage={setSelectedMessageId}
          selectedMessageId={selectedMessageId}
        />
      </div>
      
      {/* Kundöversikt Sidebar - 40% */}
      <div className="w-[40%]">
        <CustomerIntelligenceSidebarOptimized message={selectedMessage} />
      </div>
    </div>
  );
}